
/* Para asegurarnos que ejecutamos en la BBDD SPRINGFIELD */

USE SPRINGFIELD;

/* Creacion de la tabla PERSONAJES */

/* CREATE TABLE PERSONAJES
(ID_PERSONAJE INT,
DESC_PERSONAJE VARCHAR(255),
ID_FAMILIA INT,
ID_SEXO INT,
ID_MATRIMONIO INT,
ID_LUGAR_RESIDENCIA INT,
ID_PROFESION INT,
ID_LUGAR_PROFESION INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);*/

/* Vemos las tablas de la BBDD SPRINGFIELD */

/* SHOW TABLES FROM SPRINGFIELD; */

/* Ver contenido de la tabla PERSONAJES */

/* SELECT * FROM PERSONAJES*/ 

/* Borrado de la tabla PERSONAJES */

/* DROP TABLE PERSONAJES; */

/* Creacion de la tabla PERSONAJES con el nombre de la tabla mal*/

/*CREATE TABLE PRESONAJES
(ID_PERSONAJE INT,
DESC_PERSONAJE VARCHAR(255),
ID_FAMILIA INT,
ID_SEXO INT,
ID_MATRIMONIO INT,
ID_LUGAR_RESIDENCIA INT,
ID_PROFESION INT,
ID_LUGAR_PROFESION INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);*/

/* Ponemos bien el nombre de la tabla PERSONAJES */

/*RENAME TABLE PRESONAJES TO PERSONAJES;*/

/* Borrado de la tabla PERSONAJES */

/*DROP TABLE PERSONAJES;*/

/* Creacion de la tabla PERSONAJES con el nombre del campo FECHA_MODIFICACION mal*/

/*CREATE TABLE PERSONAJES
(ID_PERSONAJE INT,
DESC_PERSONAJE VARCHAR(255),
ID_FAMILIA INT,
ID_SEXO INT,
ID_MATRIMONIO INT,
ID_LUGAR_RESIDENCIA INT,
ID_PROFESION INT,
ID_LUGAR_PROFESION INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICION DATETIME);*/

/* Ponemos bien el nombre del campo FECHA_MODIFICACION*/

/*ALTER TABLE PERSONAJES CHANGE FECHA_MODIFICION FECHA_MODIFICACION DATETIME;*/

/* Ver contenido de la tabla PERSONAJES */

/* SELECT * FROM PERSONAJES*/ 

/* Cambiamos el tipo de dato del campo FECHA_MODIFICACION (1ª forma)*/

/*ALTER TABLE PERSONAJES CHANGE FECHA_MODIFICACION FECHA_MODIFICACION DATE;*/

/* Cambiamos el tipo de dato del campo FECHA_MODIFICACION (2ª forma)*/

/*ALTER TABLE PERSONAJES MODIFY FECHA_MODIFICACION DATE;*/

/* Ponemos bien el tipo de dato del campo FECHA_MODIFICACION (1ª forma)*/

/*ALTER TABLE PERSONAJES CHANGE FECHA_MODIFICACION FECHA_MODIFICACION DATETIME;*/

/* Ponemos bien el tipo de dato del campo FECHA_MODIFICACION (2ª forma)*/

/*ALTER TABLE PERSONAJES MODIFY FECHA_MODIFICACION DATETIME;*/

/* Borramos la tabla PERSONAJES */

/*DROP TABLE PERSONAJES;*/

/* Creamos la tabla PERSONAJES sin el ID_PERSONAJE, ID_FAMILIA y FECHA_MODIFICACION */

/*CREATE TABLE PERSONAJES
(DESC_PERSONAJE VARCHAR(255),
ID_SEXO INT,
ID_MATRIMONIO INT,
ID_LUGAR_RESIDENCIA INT,
ID_PROFESION INT,
ID_LUGAR_PROFESION INT,
FECHA_INSERT DATETIME);*/

/* Añadimos la FECHA_MODIFICACION al final de la tabla*/

/*ALTER TABLE PERSONAJES ADD FECHA_MODIFICACION DATETIME;*/

/* Ver contenido de la tabla PERSONAJES */

/* SELECT * FROM PERSONAJES*/ 

/* Añadimos la FECHA_MODIFICACION al principio de la tabla*/

/*ALTER TABLE PERSONAJES ADD ID_PERSONAJE INT FIRST;*/

/* Ver contenido de la tabla PERSONAJES */

/* SELECT * FROM PERSONAJES*/ 

/* Añadimos la FECHA_MODIFICACION detrás del campo DESC_PERSONAJE*/

/*ALTER TABLE PERSONAJES ADD ID_FAMILIA INT AFTER DESC_PERSONAJE;*/

/* Ver contenido de la tabla PERSONAJES */

/* SELECT * FROM PERSONAJES*/ 

/* Borramos la tabla PERSONAJES */

/*DROP TABLE PERSONAJES;*/

/* Creamos la tabla PERSONAJES bien*/

/*CREATE TABLE PERSONAJES
(ID_PERSONAJE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_PERSONAJE VARCHAR(255),
ID_FAMILIA INT,
ID_SEXO INT,
ID_MATRIMONIO INT,
ID_LUGAR_RESIDENCIA INT,
ID_PROFESION INT,
ID_LUGAR_PROFESION INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);*/

/* Creamos la tabla MASCOTAS*/

/*CREATE TABLE MASCOTAS
(ID_MASCOTA INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_MASCOTA VARCHAR(255),
ID_FAMILIA INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);*/

