USE SPRINGFIELD;

/* Creacion de la tabla FAMILIAS */

CREATE TABLE FAMILIAS
(ID_FAMILIA INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_FAMILIA VARCHAR(255),
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);

/* Creacion de la tabla PROFESIONES */

CREATE TABLE PROFESIONES
(ID_PROFESION INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_PROFESION VARCHAR(255),
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);

/* Creacion de la tabla SEXO */

CREATE TABLE SEXO
(ID_SEXO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_SEXO VARCHAR(255),
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);

/* Creacion de la tabla MATRIMONIOS */

CREATE TABLE MATRIMONIOS
(ID_MATRIMONIO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_MATRIMONIO VARCHAR(255),
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);

/* Creacion de la tabla LUGARES */

CREATE TABLE LUGARES
(ID_LUGAR INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_LUGAR VARCHAR(255),
ID_CIUDAD INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);

/* Creacion de la tabla CIUDADES */

CREATE TABLE CIUDADES
(ID_CIUDAD INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_CIUDAD VARCHAR(255),
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);

/* Creacion de la tabla FRASES */

CREATE TABLE FRASES
(ID_FRASE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESC_FRASE VARCHAR(2048),
ID_PERSONAJE INT,
FECHA_INSERT DATETIME,
FECHA_MODIFICACION DATETIME);



