USE SPRINGFIELD;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (1, "SIMPSONS", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (2, "BOUVIER", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (3, "FLANDERS", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (4, "WIGGUM", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (5, "SPUCKLER", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (6, "NAHASAPEEMAPETILON", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (7, "VAN HOUTEN", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (8, "BURNS", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (9, "MUNTZ", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (10, "SKINNER", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (11, "LOVEJOY", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (12, "HIBBERT", NOW(), NOW());
COMMIT;

INSERT INTO FAMILIAS (ID_FAMILIA, DESC_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES (13, "PRINCE", NOW(), NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (1, "HOMER & MARGE SIMPSON", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (2, "NEDD & MAUDE FLANDERS", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (3, "CLANCY & SARAH WIGGUM", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (4, "TIMOTHY & HELEN LOVEJOY", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (5, "APU & MANJULA NAHASAPEEMAPETILON", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (6, "KIRK & LUANN FLANDERS", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (7, "POPPA & LILI MUNTZ", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (8, "SHELDON & AGNES SKINNER", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (9, "JULIUS & BERNICE HIBBERT", NOW(),NOW());
COMMIT;

INSERT INTO MATRIMONIOS (ID_MATRIMONIO, DESC_MATRIMONIO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (10, "MARTIN & MARTHA SIMPSON", NOW(),NOW());
COMMIT;

INSERT INTO SEXO (ID_SEXO, DESC_SEXO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (1, "HOMBRE", NOW(),NOW());
COMMIT;

INSERT INTO SEXO (ID_SEXO, DESC_SEXO, FECHA_INSERT, FECHA_MODIFICACION) VALUES (2, "MUJER", NOW(),NOW());
COMMIT;



