USE SPRINGFIELD;

SELECT * FROM FAMILIAS;

INSERT INTO MASCOTAS (DESC_MASCOTA, ID_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES ('AYUDANTE DE SANTA CLAUS',1,NOW(),NOW());

INSERT INTO MASCOTAS (DESC_MASCOTA, ID_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES ('BOLA DE NIEVE II',1,NOW(),NOW());

INSERT INTO MASCOTAS (DESC_MASCOTA, ID_FAMILIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES ('JUB-JUB',2,NOW(),NOW());

COMMIT;

SELECT * FROM MASCOTAS;