USE SPRINGFIELD;

/*Tabla LUGARES*/

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CASTILLO DEL JUBILADO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA TABERNA DE MOE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PLANTA NUCLEAR",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESCUELA DE PRIMARIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL BADULAQUE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("KRUSTY BURGUER",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL CALABOZO EL ANDROIDE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("IGLESIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESTADIO DE LOS ISOTOPOS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CENTRO COMERCIAL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("AEROPUERTO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HOSPITAL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PENITENCIARIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CASINO DEL SR.BURNS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MONTAÑA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("RESTAURANTE LUIGI",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CEMENTERIO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESTUDIOS KRUSTY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA CORTE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("QUEMA DE LLANTAS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MUSEO SPRINGSONIANO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("FABRICA DE CAJAS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MUSEO DEL SELLO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BOOKACCINO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("I CANT BELIEVE ITS A LAW FIRM",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DONNERS PARTY SUPPLIES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("IN N OUT EAR PUERCING",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CAPTAIN BLIP ZAPATERIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CRAZY E.T.S PRHONE HOME",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("GIRDLES N SUCH",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("KIDSTOWN USA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ROPA DINGO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ALL CREATURE GREAT AND CHEAP",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("IRCHY & SCRATCHYS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("INTERNATIONAL HOUSE OF ANSWERING MACHINES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("I.P.O FRIDAYS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE TAM O SHANTER CONNECTION",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("WEE MONSIEUR",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE CHINA SYNDROME",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE JERKY HUT",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SWEET HOME ALABAMA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MARTIAL ARTS ACADEMY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("GOODY NEW SHOES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HAILSTONES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE EAR PIERCERY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PLUNDERER PETES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ROCK BOTTOM REMAINDERS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HUNTING SUPPLIES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE VAST WAISTBAND",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TOMMY HILLCLIMBER",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MAPPLE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DA BUZZ CLUB",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HAPPY SAILOR TATOO PARLOR",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA TRUFA DORADA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LARD LAD DONUTS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL MATADERO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PHINEAS EL MANTECOSO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE HAPPY SUMO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("WALL-E-WEASELS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("IZZYS DELI",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL HOLANDES FRITO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL PLANET HYPE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA CASA MUNICIPAL DE PANQUEQUES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL LAGO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL SPRINGFIELD GLACIER",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA CUEVA DEL PADRE DE CARL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL CANYON DE SPRINGFIELD",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PAPALINA GEORGE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SOCIEDAD HISTORICA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PARQUE NACIONAL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CENTRO DE CONVENCIONES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL CUERNO DE LA MUERTE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA PEQUEÑA CAJA NEGRA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL LEGITIMO CLUB SOCIAL DE EMPRESARIOS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SLEEP-EAZY MOTEL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL RANCHO RELAXO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HOTEL WOOSTERFIELD",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("YE OLDE OFF-RAMP INN",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("INN APHRODITE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PALMA SPRINGFIELD RESORT",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SEGUNDO BEST-WESTERN HOTEL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SNUGGLER COVE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("STARLIGHT MOTEL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HOSPITAL MENTAL BOSQUECALMO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLINICA DERMATOLOGICA DEL DR.ZITSOFSKY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HAIR CLINIC",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLINICA MAYO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EYE CARAMBA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("UNIVERSIDAD",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESCUELA SECUNDARIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLOISTERS ACADEMY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ZURDORIUM",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MONSTRUO MERCADO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CASA DE ARMAS Y ANTIGUEDADES HERMAN",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL DESPARRAMART",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("GROCERY STORE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("A VER SI AHORRA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA FLORIST",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("KING TOOTS MUSIC STORE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CIRCUIT CIRCUS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE FOOD FACTORY TAILANDES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BARNEY BOWL-A-RAMA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA MANSION DERRIERE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE JAVA SERVER",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CAMPAMENTO KRUSTY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CHEZ GUEVARA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ZOOMINATOR",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MONTE SPLASH",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESTADIO DUFF",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TEATRO AZTECA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("NOISELAND VIDEO ARCADE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EL ACUEDUCTO ABANDONADO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BLOCKOLAND",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CIRCUITO DE CARRERAS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA SKATES N SUCH ICE RINK",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLUB 4-H",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CINES GOOGOLPLEX",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CALLE FALSA 123",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PRISION DE MINIMA SEGURIDAD",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("RACAPICALANDIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MUELLE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DEPARTAMENTO DE POLICIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESTACION KBBL RADIO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("AYUNTAMIENTO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JUBILANDIA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("OBSERVATORIO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CATEDRAL DE CRISTAL",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LA ROCA DEL CARROZA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TEMPLO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CIRCUITO DE GALGOS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PRESA",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BARRIO JUDIO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BARRIO RUSO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DEPARTAMENTO DE TRAFICO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("POWELL MOTORS",12,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("FABRICA DE TRADUCTORES DE BEBES",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ESTACION DE METRO (CALLE 3A)",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BUMTOWN",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CATFISH LAKE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("AVENIDA 12TH",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BETTERTHANTV.COM",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ZIFFCORP",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("VERTEDERO DE DESECHOS TÓXICOS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("FUERTE SPRINGFIELD",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PRIMER BANCO DE SPRINGFIELD",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DETROIT",12,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("742 EVERGREEN TERRACE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("744 EVERGREEN TERRACE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("790 EVERGREEN TERRACE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CASA SPUCKLER",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("APARTAMENTO 38",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("746 EVERGREEN TERRACE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("FABRICA DE GALLETAS SOUTHERN CRACKER",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LOMAS DE SPRINGFIELD - MANSION BURNS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CASA DE LOS MUNTZ",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("734 EVERGREEN TERRACE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("THE PRINCE HOUSE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("82 EVERGREEN TERRACE",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LOMAS DE SPRINGFIELD - CASA DE TONY EL GORDO",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LOMAS DE SPRINGFIELD - MANSION DE KRUSTY",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TIENDA DE COMICS",1,NOW(),NOW());

INSERT INTO LUGARES (DESC_LUGAR, ID_CIUDAD, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CANAL 6",1,NOW(),NOW());

COMMIT; 

SELECT * FROM LUGARES;

/*Tabla PERSONAJES*/

INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ABRAHAM SIMPSON",1,1,1,1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HOMER SIMPSON",1,1,1,147,5,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LISA SIMPSON",1,2,147,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MARGE SIMPSON",1,2,1,147,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BART SIMPSON",1,1,147,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MAGGIE SIMPSON",1,2,147,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HERBERT POWELL",1,1,12,2,135,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SELMA BOUVIER",2,2,6,134,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("PATTY BOUVIER",2,2,6,134,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JACQUELINE BOUVIER",2,2,1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("NEDD FLANDERS",2,1,2,148,2,92,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TODD FLANDERS",3,1,148,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ROD FLANDERS",3,1,148,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MAUDE FLANDERS",2,1,2,148,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLANCY WIGGUM",4,1,3,149,7,122,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SARAH WIGGUM",4,2,3,149,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("RALPH WIGGUM",4,1,149,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLETUS SPUCKLER",5,1,150,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BRANDINE SPUCKLER",5,2,150,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("APU NAHASAPEEMAPETILON",6,1,5,151,2,5,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MANJULA NAHASAPEEMAPETILON",6,2,5,151,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MILHOUSE VAN HOUTEN",7,1,152,2,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("KIRK VAN HOUTEN",7,1,6,152,8,153,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LUANN VAN HOUTEN",7,2,6,152,9,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CHARLES MONTGOMERY BURNS",8,1,154,2,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LARRY BURNS",8,1,8,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DAPHNE BURNS",8,2,1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CLIFFORD BURNS",8,1,1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LILI MUNTZ",9,2,7,155,10,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("NELSON MUNTZ",9,1,155,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("POPPA MUNTZ",9,1,7,155,11,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("WALTER SEYMOUR SKINNER",10,1,12,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("AGNES SKINNER",10,2,8,1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("WALTER SEYMOUR SKINNER",10,1,13,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SHELDON SKINNER",10,1,8,14,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TIMOTHY LOVEJOY",11,1,4,12,8,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HELEN LOVEJOY",11,2,4,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JESSICA LOVEJOY",11,2,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MURPHY HIBBERT",12,1,16,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BERNICE HIBBERT",12,2,9,156,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JULIUS HIBBERT",12,1,9,156,17,12,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MARTIN PRINCE SR",13,1,4,157,18,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MARTIN PRINCE JR.",13,1,157,3,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_FAMILIA, ID_SEXO, ID_MATRIMONIO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MARTHE PRINCE",13,1,4,157,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EDNA KRABAPAPPEL",2,158,19,4,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MOE SZYSLAK",1,156,2,2,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TONY EL GORDO",1,159,20,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HERSCHEL SHMOIKEL PINKUS YEROCHAM KRUSTOFSKY",1,160,21,18,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("WAYLON SMITHERS",1,22,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BARNEY GUMBLE",1,23,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LOU",1,24,122,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("EDDIE",1,24,122,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("SAM",1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LARRY",1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LENNY LEONARD",1,5,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CARL CARLSON",1,25,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MINDY SIMMONS",2,26,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_LUGAR_RESIDENCIA, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JASPER BEARDLEY",1,1,1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("ROBERT UNDERDUNK TERWILLIGER JR",1,27,18,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("CHESTER TURLEY",1,28,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("HANS TOPO",1,29,3,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("DISCOTEQUE STUART",1,30,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("YARITZA BURGOS",1,31,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("BARRY HUFFMAN",1,32,109,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MELVIN VAN HORNE",1,27,18,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JEFF ALBERSTON",1,33,161,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("LIONEL HUTZ",1,34,25,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("KENT BROCKMAN",1,21,162,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("STEPHANIE BROCKMAN",2,35,162,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("TROY MCCLURE",1,31,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("GERALDS SAMSON",1,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("MARVIN MONROE",1,36,84,NOW(),NOW());
INSERT INTO PERSONAJES (DESC_PERSONAJE, ID_SEXO, ID_PROFESION, ID_LUGAR_PROFESION, FECHA_INSERT, FECHA_MODIFICACION) VALUES ("JOSEPH FITZPATRICK FITGERALD FITZHENRY QUIMBY",1,37,124,NOW(),NOW());

COMMIT;

SELECT * FROM PERSONAJES;

/*Rellenar tabla desde archivo de texto local.*/

LOAD DATA LOCAL INFILE
'/home/springfield/Documentos/Curso BBDD/frases.txt'
INTO TABLE FRASES
FIELDS TERMINATED BY '|' ENCLOSED BY '' ESCAPED BY'';

SELECT * FROM FRASES;


