USE SPRINGFIELD;

/*Usando un alias para la tabla, en este caso el alias es PER*/
SELECT ID_PERSONAJE
, PER.DESC_PERSONAJE
, PER.ID_FAMILIA
, PER.ID_SEXO
, SEXO.DESC_SEXO /*Mostramos la descripción del sexo*/
, PER.ID_MATRIMONIO
, PER.ID_LUGAR_RESIDENCIA
, PER.ID_PROFESION
, PER.ID_LUGAR_PROFESION
FROM PERSONAJES PER
, SEXO SEXO
WHERE PER.ID_SEXO=SEXO.ID_SEXO
ORDER BY ID_PERSONAJE
;

/*Manera más habitual de hacer INNER_JOIN (es más rápido, eficiente), 
pero cuidado con los campos NULL porque no mostraría bien los resultados.*/

SELECT ID_PERSONAJE
, PER.DESC_PERSONAJE
, PER.ID_FAMILIA
, PER.ID_SEXO
, SEXO.DESC_SEXO
, PER.ID_MATRIMONIO
, PER.ID_LUGAR_RESIDENCIA
, PER.ID_PROFESION
, PER.ID_LUGAR_PROFESION
FROM PERSONAJES PER
INNER JOIN SEXO SEXO ON PER.ID_SEXO=SEXO.ID_SEXO
;

/*Para evitar problemas se puede cambiar el tipo de dato,
así aseguramos que el campo que nos interesa tiene obligatariamente registros.*/

ALTER TABLE PERSONAJES MODIFY ID_SEXO INT(11) NOT NULL;

INNER JOIN mostrando descripcion de familia,
(solo se mostrarán los registros que no sean NULL)

SELECT ID_PERSONAJE
, PER.DESC_PERSONAJE
, PER.ID_FAMILIA
, FAM.DESC_FAMILIA
, PER.ID_SEXO
, SEXO.DESC_SEXO
, PER.ID_MATRIMONIO
, PER.ID_LUGAR_RESIDENCIA
, PER.ID_PROFESION
, PER.ID_LUGAR_PROFESION
FROM PERSONAJES PER
INNER JOIN SEXO SEXO ON PER.ID_SEXO=SEXO.ID_SEXO
INNER JOIN FAMILIAS FAM ON PER.ID_FAMILIA=FAM.ID_FAMILIA
;

/*Con LEFT OUTER JOIN (la tabla de la izquierda, la primera tabla)
se muestran todos los registros, incluidos los que sean NULL*/

SELECT ID_PERSONAJE
, PER.DESC_PERSONAJE
, PER.ID_FAMILIA
, FAM.DESC_FAMILIA
, PER.ID_SEXO
, SEXO.DESC_SEXO
, PER.ID_MATRIMONIO
, PER.ID_LUGAR_RESIDENCIA
, PER.ID_PROFESION
, PER.ID_LUGAR_PROFESION
FROM PERSONAJES PER
INNER JOIN SEXO SEXO ON PER.ID_SEXO=SEXO.ID_SEXO
LEFT OUTER JOIN FAMILIAS FAM ON PER.ID_FAMILIA=FAM.ID_FAMILIA
;

/*Podemos indicar que muestre algo descriptivo en los campos que sean NULL*/

SELECT ID_PERSONAJE
, PER.DESC_PERSONAJE
, PER.ID_FAMILIA
, IFNULL(FAM.DESC_FAMILIA,'DESCONOCIDO') DESC_FAMILIA
, PER.ID_SEXO
, SEXO.DESC_SEXO
, PER.ID_MATRIMONIO
, PER.ID_LUGAR_RESIDENCIA
, PER.ID_PROFESION
, PER.ID_LUGAR_PROFESION
FROM PERSONAJES PER
INNER JOIN SEXO SEXO ON PER.ID_SEXO=SEXO.ID_SEXO
LEFT OUTER JOIN FAMILIAS FAM ON PER.ID_FAMILIA=FAM.ID_FAMILIA
;