USE SPRINGFIELD;

/*INTERSECT y MINUS no existen en MySQL.*/

UPDATE TMP_PERSONAJES SET ID_MATRIMONIO=10 WHERE ID_PERSONAJE IN(42,44);
COMMIT;


/*Para evitar los registros NULL se pone <=> en los campos que pueden tener NULL*/

SELECT *
FROM PERSONAJES A
INNER JOIN TMP_PERSONAJES B ON A.ID_PERSONAJE=B.ID_PERSONAJE
AND A.DESC_PERSONAJE=B.DESC_PERSONAJE
AND A.ID_FAMILIA<=>B.ID_FAMILIA
AND A.ID_SEXO=B.ID_SEXO
AND A.ID_MATRIMONIO<=>B.ID_MATRIMONIO
AND A.ID_LUGAR_RESIDENCIA<=>B.ID_LUGAR_RESIDENCIA
AND A.ID_PROFESION<=>B.ID_PROFESION
AND A.ID_LUGAR_PROFESION<=>B.ID_LUGAR_PROFESION
AND A.FECHA_INSERT=B.FECHA_INSERT
AND A.FECHA_MODIFICACION=B.FECHA_MODIFICACION
;

/*Consulta dentro de consulta, es una subquery
La siguiente consulta es equivalente a INTERSECT, devuelve todos los campos que estén en las dos tablas.*/

SELECT *
FROM PERSONAJES A
WHERE EXISTS (SELECT *
FROM TMP_PERSONAJES B
WHERE A.ID_PERSONAJE=B.ID_PERSONAJE
AND A.DESC_PERSONAJE=B.DESC_PERSONAJE
AND A.ID_FAMILIA<=>B.ID_FAMILIA
AND A.ID_SEXO=B.ID_SEXO
AND A.ID_MATRIMONIO<=>B.ID_MATRIMONIO
AND A.ID_LUGAR_RESIDENCIA<=>B.ID_LUGAR_RESIDENCIA
AND A.ID_PROFESION<=>B.ID_PROFESION
AND A.ID_LUGAR_PROFESION<=>B.ID_LUGAR_PROFESION
AND A.FECHA_INSERT=B.FECHA_INSERT
AND A.FECHA_MODIFICACION=B.FECHA_MODIFICACION)
;

/*Ejemplo de MINUS (devolvería los registro de la tabla2 que no estén en la tabla1,
y en la siguiente lo contrario)*/

SELECT * 
FROM TABLA1
MINUS
SELECT * 
FROM TABLA2;

SELECT * 
FROM TABLA2
MINUS
SELECT * 
FROM TABLA1;


/*Con NOT EXISTS se simula el comando MINUS*/

SELECT *
FROM PERSONAJES A
WHERE NOT EXISTS (SELECT *
FROM TMP_PERSONAJES B
WHERE A.ID_PERSONAJE=B.ID_PERSONAJE
AND A.DESC_PERSONAJE=B.DESC_PERSONAJE
AND A.ID_FAMILIA<=>B.ID_FAMILIA
AND A.ID_SEXO=B.ID_SEXO
AND A.ID_MATRIMONIO<=>B.ID_MATRIMONIO
AND A.ID_LUGAR_RESIDENCIA<=>B.ID_LUGAR_RESIDENCIA
AND A.ID_PROFESION<=>B.ID_PROFESION
AND A.ID_LUGAR_PROFESION<=>B.ID_LUGAR_PROFESION
AND A.FECHA_INSERT=B.FECHA_INSERT
AND A.FECHA_MODIFICACION=B.FECHA_MODIFICACION)
;

SELECT *
FROM TMP_PERSONAJES A
WHERE NOT EXISTS (SELECT *
FROM PERSONAJES B
WHERE A.ID_PERSONAJE=B.ID_PERSONAJE
AND A.DESC_PERSONAJE=B.DESC_PERSONAJE
AND A.ID_FAMILIA<=>B.ID_FAMILIA
AND A.ID_SEXO=B.ID_SEXO
AND A.ID_MATRIMONIO<=>B.ID_MATRIMONIO
AND A.ID_LUGAR_RESIDENCIA<=>B.ID_LUGAR_RESIDENCIA
AND A.ID_PROFESION<=>B.ID_PROFESION
AND A.ID_LUGAR_PROFESION<=>B.ID_LUGAR_PROFESION
AND A.FECHA_INSERT=B.FECHA_INSERT
AND A.FECHA_MODIFICACION=B.FECHA_MODIFICACION)
;

/*Borro tablas auxiliares*/

DROP TABLE TMP_PERSONAJES;

DROP TABLE TMP_PERSONAJES_HOMBRES;

DROP TABLE TMP_PERSONAJES_MUJERES;