USE SPRINGFIELD;

SELECT *
FROM PROFESIONES;

SELECT DESC_PROFESION
FROM PROFESIONES;

SELECT DISTINCT DESC_PROFESION
FROM PROFESIONES;

SELECT COUNT(*) TOTAL_PROFESIONES
FROM PROFESIONES;

/*Mostrar sexo de los personajes*/

SELECT PER.DESC_PERSONAJE, SEXO.DESC_SEXO
FROM PERSONAJES PER
, SEXO SEXO
WHERE PER.ID_SEXO=SEXO.ID_SEXO
;

/*Lo mismo utilizando INNER JOIN, la manera standar de hacerlo*/

SELECT PER.DESC_PERSONAJE, SEXO.DESC_SEXO
FROM PERSONAJES PER
INNER JOIN SEXO SEXO ON PER.ID_SEXO=SEXO.ID_SEXO
;

/*Cuántos hombres y cuantas mujeres hay en la base de datos*/

SELECT SEXO.DESC_SEXO, COUNT(*) TOTAL
FROM PERSONAJES PER
INNER JOIN SEXO SEXO ON PER.ID_SEXO=SEXO.ID_SEXO
GROUP BY SEXO.DESC_SEXO
;


/*Dónde viven los personajes, incluidos los nulos.*/

SELECT PER.DESC_PERSONAJE, LUG.DESC_LUGAR DESC_LUGAR_RESIDENCIA
FROM PERSONAJES PER
LEFT OUTER JOIN LUGARES LUG ON PER.ID_LUGAR_RESIDENCIA=LUG.ID_LUGAR
;

/*Qué personajes viven y trabajan en su casa.
<=> También muestra los registros nulos.*/

SELECT DESC_PERSONAJE, ID_LUGAR_RESIDENCIA, ID_LUGAR_PROFESION
FROM PERSONAJES
WHERE ID_LUGAR_RESIDENCIA<=>ID_LUGAR_PROFESION
;

/*Cuántos personajes hay que no sean de la familia Simpsons ni de la familia Flanders.*/

SELECT PER.DESC_PERSONAJE, FAM.DESC_FAMILIA
FROM PERSONAJES PER
LEFT OUTER JOIN FAMILIAS FAM ON PER.ID_FAMILIA=FAM.ID_FAMILIA
WHERE FAM.DESC_FAMILIA NOT IN ('SIMPSONS', 'FLANDERS') OR ISNULL(FAM.DESC_FAMILIA)
;
