USE SPRINGFIELD;

DROP TABLE IF EXISTS TMP_PERSONAJES_ENCRIPTADOS;

CREATE TABLE TMP_PERSONAJES_ENCRIPTADOS
(DESC_PERSONAJE VARCHAR(255)
, CLAVE VARCHAR(255));

DROP TRIGGER IF EXISTS trigger_clave;

CREATE TRIGGER trigger_clave BEFORE INSERT ON TMP_PERSONAJES_ENCRIPTADOS
FOR EACH ROW SET NEW.CLAVE=MD5(NEW.DESC_PERSONAJE);